
export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'homeCenter',
    path: '/home',
    title: 'Home',
    requiresAuth: true,
    icon: 'line-md:home',
    componentPath: '/demo/userCenter/index.vue',
    id: 89,
    pid: null,
  },


  {
    name: 'Cluster Management',
    path: '/cluster-management',
    title: 'Cluster Management',
    requiresAuth: true,
    icon: 'icon-park-outline:alarm',
    // menuType: 'dir',
    componentPath: "/KubeSage/ClusterManagement.vue",
    id: 4,
    pid: null,
  },
 
  {
    name: 'Cluster Analysis',
    path: '/cluster-analysis',
    title: 'Cluster Analysis',
    requiresAuth: true,
    icon: 'icon-park-outline:error-computer',
    componentPath: '/KubeSage/ClusterManagement.vue',
    id: 31,
    pid: null,
  },
  {
    name: 'Chat with KubeSage',
    path: '/chat-with-kubesage',
    title: 'KubeSage Chat',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/KubeSage/chat.vue',
    id: 32,
    pid: null,
  },

  {
    name: 'Auth Settings',
    path: '/auth-settings',
    title: 'Auth Settings',
    requiresAuth: true,
    icon: 'icon-park-outline:setting',
    // menuType: 'dir',
    componentPath: '/KubeSage/ClusterManagement.vue',
    id: 33,
    pid: null,
  },
  


 
  // {
  //   name: 'Kubernetes',
  //   path: '/multi/multi3',
  //   title: 'Kubernetes',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:server',
  //   menuType: 'dir',
  //   componentPath: null,
  //   id: 8,
  //   pid: 4,
  // },
  // {
  //   name: 'Cluster Details',
  //   path: '/infra-orc/kubernetes/cluster',
  //   title: 'Cluster Details',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   componentPath: '/infra-orc/kubernetes/cluster.vue',
  //   id: 9,
  //   pid: 8,
  // },
  // {
  //   name: 'Cluster Overview',
  //   path: '/infra-orc/kubernetes/overview',
  //   title: 'Cluster Overview',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   componentPath: '/infra-orc/kubernetes/overview.vue',
  //   id: 201,
  //   pid: 8,
  // },
  // {
  //   name: 'Namespace',
  //   path: '/infra-orc/kubernetes/namespace',
  //   title: 'Namespace',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   componentPath: '/infra-orc/kubernetes/namespace.vue',
  //   id: 9,
  //   pid: 8,
  // },
  // {
  //   name: 'Pod',
  //   path: '/infra-orc/kubernetes/pods',
  //   title: 'Pods',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   componentPath: '/infra-orc/kubernetes/pods.vue',
  //   id: 9,
  //   pid: 8,
  // },
  // {
  //   name: 'containers',
  //   path: '/infra-orc/kubernetes/container',
  //   title: 'Containers',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   componentPath: '/infra-orc/kubernetes/container.vue',
  //   id: 9,
  //   pid: 8,
  // },
  // {
  //   name: 'Node',
  //   path: '/infra-orc/kubernetes/nodes',
  //   title: 'Nodes',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   componentPath: '/infra-orc/kubernetes/nodes.vue',
  //   id: 9,
  //   pid: 8,
  // },

  // {
  //   name: 'Docker',
  //   path: '/multi/multi2',
  //   title: 'Docker',
  //   requiresAuth: true,
  //   // icon: 'icon-park-outline:list',
  //   icon: 'icon-park-outline:list-view',

  //   menuType: 'page',
  //   componentPath: '/infra-orc/docker.vue',
  //   id: 6,
  //   pid: 4,
  // },
  
  // {
  //   name: 'Application',
  //   path: '/error',
  //   title: 'Application',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:error-computer',
  //   menuType: 'dir',
  //   componentPath: null,
  //   id: 31,
  //   pid: null,
  // },
  // {
  //   name: 'NetworkPerformance',
  //   path: '/apm-dashboard/apm',
  //   title: 'Microservice',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   order: 3,
  //   componentPath: '/apm-dashboard/apm.vue',
  //   id: 32,
  //   pid: 31,
  // },



  // // {
  // //   name: 'Monolithic',
  // //   path: '/monolithic',
  // //   title: 'Monolithic',
  // //   requiresAuth: true,
  // //   icon: 'icon-park-outline:list',
  // //   menuType: 'dir',
  // //   componentPath: null,
  // //   id: 33,
  // //   pid: 31,
  // // },

  // // {
  // //   name: 'Java',
  // //   path: '/monolithic/java',
  // //   title: 'Java',
  // //   requiresAuth: true,
  // //   icon: 'icon-park-outline:list',
  // //   componentPath: '/monolithic/java.vue',
  // //   order: 5,
  // //   id: 131,
  // //   pid: 33,
  // // },

  
  // {
  //   name: 'userSetting',
  //   path: '/Onboard/Agent',
  //   title: 'Agent',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:every-user',
  //   componentPath: '/setting/account/index.vue',
  //   id: 37,
  //   pid: 36,
  // },
  // {
  //   name: 'generalSetting',
  //   path: '/AddOns/Plugins',
  //   title: 'Plugins',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:plug-one',
  //   componentPath: '/onboard/plugins/plugins.vue',
  //   id: 53,
  //   pid: 200,
  // },
  // {
  //   name: 'Linux Client Registration',
  //   path: '/Onboard/Linux',
  //   title: 'Linux Client Registration',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   componentPath: '/onboard/linux/index.vue',
  //   id: 50,
  //   pid: 36,
  // },
  // {
  //   name: 'Windows Client Registration',
  //   path: '/Onboard/Windows',
  //   title: 'Windows Client Registration',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:windows',
  //   componentPath: '/onboard/windows/index.vue',
  //   id: 51,
  //   pid: 36,
  // },
  
 
  
  // {
  //   name: 'SOC Wazuh',
  //   path: '/soc',
  //   title: 'SOC Wazuh',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:book-one',
  //   hide: true,
  //   // menuType: 'dir',
  //   componentPath: '/SOC_Wazuh/soc.vue',
  //   id: 39,
  //   pid: null,

  // },
  // {
  //   name: 'Wazuh2',
  //   path: '/wazuh2', // Unique path for Wazuh2
  //   title: 'Wazuh2',
  //   requiresAuth: true,
  //   icon: 'carbon:data-error',
  //   hide: true,
  //   // menuType: 'dir',
  //   componentPath: '/Wazuh2/wazuh2.vue',
  //   id: 40,
  //   pid: null,
  // },
  // {
  //   name: 'Wazuh3',
  //   path: '/wazuh3', // Unique path for Wazuh2
  //   title: 'Wazuh3',
  //   requiresAuth: true,
  //   icon: 'carbon:data-error',
  //   hide: true,
  //   // menuType: 'dir',
  //   componentPath: '/Wazuh3/wazuh3.vue',
  //   id: 41,
  //   pid: null,

  // },

  // {
  //   name: 'summary',
  //   path: '/summary',
  //   title: 'Summary',
  //   requiresAuth: true,
  //   hide: true,
  //   icon: 'icon-park-outline:book-one',
  //   componentPath: '/activatedPlugin/summary.vue',
  //   id: 44,
  //   pid: null,
  // },
  // {
  //   name: 'compliance',
  //   path: '/compliance',
  //   title: 'Compliance',
  //   requiresAuth: true,
  //   hide: true,
  //   icon: 'icon-park-outline:book-one',
  //   componentPath: '/activatedPlugin/compliance.vue',
  //   id: 45,
  //   pid: null,
  // },
  // {
  //   name: 'fileIntegrity',
  //   path: '/fileIntegrity',
  //   title: 'File Integrity Monitoring',
  //   requiresAuth: true,
  //   hide: true,
  //   icon: 'icon-park-outline:book-one',
  //   componentPath: '/activatedPlugin/fileIntegrity.vue',
  //   id: 46,
  //   pid: null,
  // },
  // {
  //   name: 'mitreAttack',
  //   path: '/mitreAttack',
  //   title: 'Mitre Attack',
  //   requiresAuth: true,
  //   hide: true,
  //   icon: 'icon-park-outline:book-one',
  //   componentPath: '/activatedPlugin/mitreAttack.vue',
  //   id: 47,
  //   pid: null,
  // },
  // {
  //   name: 'windowsEvent',
  //   path: '/windowsEvent',
  //   title: 'Windows Event Logs',
  //   requiresAuth: true,
  //   hide: true,
  //   icon: 'icon-park-outline:book-one',
  //   componentPath: '/activatedPlugin/windowsEvent.vue',
  //   id: 48,
  //   pid: null,
  // },

  // {
  //   name: "Databases",
  //   path: "/databases",
  //   title: "Databases",
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:database-config',
  //   componentPath: "/databases/index.vue",
  //   id: 100,
  //   pid: null
  // },
  // {
  //   name: "Postgres",
  //   path: "/databases/postgres",
  //   title: "PostgreSQL",
  //   requiresAuth: true,
  //   hide: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/databases/postgres.vue",
  //   id: 101,
  //   pid: null
  // },
  // {
  //   name: "MongoDB",
  //   path: "/databases/mongodb",
  //   title: "MongoDB",
  //   requiresAuth: true,
  //   hide: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/databases/mongodb.vue",
  //   id: 102,
  //   pid: null
  // },
  // {
  //   name: "MySQL",
  //   path: "/databases/mysql",
  //   title: "MySQL",
  //   requiresAuth: true,
  //   hide: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/databases/mysql.vue",
  //   id: 103,
  //   pid: null
  // },
  // {
  //   name: "MS SQL",
  //   path: "/databases/mssql",
  //   title: "Microsoft SQL Server",
  //   requiresAuth: true,
  //   hide: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/databases/mssql.vue",
  //   id: 104,
  //   pid: null
  // },
  // {
  //   name: "Oracle DB",
  //   path: "/databases/oracledb",
  //   title: "Oracle DB",
  //   requiresAuth: true,
  //   hide: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/databases/oracle.vue",
  //   id: 105,
  //   pid: null
  // },
  // {
  //   name: 'Onboard',
  //   path: '/Onboard',
  //   title: 'Onboard',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:setting',
  //   menuType: 'dir',
  //   componentPath: null,
  //   id: 36,
  //   pid: null,
  // },
  // {
  //   name: 'Ad-Ons',
  //   path: '/AddOns',
  //   title: 'Ad-Ons',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:app-store',
  //   menuType: 'dir',
  //   componentPath: null,
  //   id: 200,
  //   pid: null,
  // },
  

]

