
export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'homeCenter',
    path: '/home',
    title: 'Home',
    requiresAuth: true,
    icon: 'line-md:home',
    componentPath: '/demo/userCenter/index.vue',
    id: 89,
    pid: null,
  },
  // {
  //   name: 'dashboard',
  //   path: '/dashboard',
  //   title: 'Dashboard',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:analysis',
  //   componentPath: '/monitoring/dashboard.vue',
  //   id: 1,
  //   pid: null,
  // },
  // {
  //   name: 'Linux Dashboard',
  //   path: '/monitoring/linux',
  //   title: 'Linux Dashboard',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   pinTab: true,
  //   hide: true,
  //   menuType: 'page',
  //   componentPath: '/monitoring/linux.vue',
  //   id: 2,
  //   pid: null,
  // },
  // {
  //   name: 'Window Dashboard',
  //   path: '/monitoring/windows',
  //   title: 'Windows Dashboard',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   menuType: 'page',
  //   hide: true,
  //   componentPath: '/monitoring/windows-m.vue',

  //   id: 3,
  //   pid: null,
  // },

  {
    name: 'Infrastructure Orchestration',
    path: '/multi',
    title: 'Infrastructure Orchestration',
    requiresAuth: true,
    icon: 'icon-park-outline:alarm',
    menuType: 'dir',
    componentPath: null,
    id: 4,
    pid: null,
  },

 
  {
    name: 'Kubernetes',
    path: '/multi/multi3',
    title: 'Kubernetes',
    requiresAuth: true,
    icon: 'icon-park-outline:server',
    menuType: 'dir',
    componentPath: null,
    id: 8,
    pid: 4,
  },
  {
    name: 'Cluster Details',
    path: '/infra-orc/kubernetes/cluster',
    title: 'Cluster Details',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/cluster.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'Cluster Overview',
    path: '/infra-orc/kubernetes/overview',
    title: 'Cluster Overview',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/overview.vue',
    id: 201,
    pid: 8,
  },
  {
    name: 'Namespace',
    path: '/infra-orc/kubernetes/namespace',
    title: 'Namespace',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/namespace.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'Pod',
    path: '/infra-orc/kubernetes/pods',
    title: 'Pods',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/pods.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'containers',
    path: '/infra-orc/kubernetes/container',
    title: 'Containers',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/container.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'Node',
    path: '/infra-orc/kubernetes/nodes',
    title: 'Nodes',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/nodes.vue',
    id: 9,
    pid: 8,
  },
 
  // {
  //   name: 'Configuration',
  //   path: '/infra-orc/kubernetes/configuration',
  //   title: 'Configuration',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   componentPath: '/infra-orc/kubernetes/configuration.vue',
  //   id: 9,
  //   pid: 8,
  // },
  {
    name: 'Docker',
    path: '/multi/multi2',
    title: 'Docker',
    requiresAuth: true,
    // icon: 'icon-park-outline:list',
    icon: 'icon-park-outline:list-view',

    menuType: 'page',
    componentPath: '/infra-orc/docker.vue',
    id: 6,
    pid: 4,
  },
  
  {
    name: 'Application',
    path: '/error',
    title: 'Application',
    requiresAuth: true,
    icon: 'icon-park-outline:error-computer',
    menuType: 'dir',
    componentPath: null,
    id: 31,
    pid: null,
  },
  {
    name: 'NetworkPerformance',
    path: '/apm-dashboard/apm',
    title: 'Microservice',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    order: 3,
    componentPath: '/apm-dashboard/apm.vue',
    id: 32,
    pid: 31,
  },
  // {
  //   name: 'Alert&IRM',
  //   path: '/demo',
  //   title: 'Alert and IRM',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:application-one',
  //   menuType: 'dir',
  //   componentPath: null,
  //   id: 13,
  //   pid: null,
  // },
  // {
  //   name: 'Oncall',
  //   path: '/demo/fetch',
  //   title: 'Oncall',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:international',
  //   componentPath: '/demo/fetch/index.vue',
  //   id: 5,
  //   pid: 13,
  // },
  // {
  //   name: 'Alerting',
  //   path: '/demo/echarts',
  //   title: 'Alerting',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:chart-proportion',
  //   componentPath: '/demo/echarts/index.vue',
  //   id: 15,
  //   pid: 13,
  // },
  
 
  
  // {
  //   name: 'NetworkPerformances',
  //   path: '/apm-dashboard/Synthetic',
  //   title: 'Synthetic Dashbaord',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   order: 3,
  //   componentPath: '/apm-dashboard/synthetic.vue',
  //   id: 33,
  //   pid: 31,
  // },

  {
    name: 'Monolithic',
    path: '/monolithic',
    title: 'Monolithic',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    menuType: 'dir',
    componentPath: null,
    id: 33,
    pid: 31,
  },

  {
    name: 'Java',
    path: '/monolithic/java',
    title: 'Java',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/monolithic/java.vue',
    order: 5,
    id: 131,
    pid: 33,
  },

  // {
  //   name: 'Administration',
  //   path: '/setting',
  //   title: 'Administration',
  //   requiresAuth: true,
  //   icon: 'carbon:user-avatar-filled-alt', 
  //   menuType: 'dir',
  //   componentPath: null,
  //   id: 35,
  //   pid: null,
  // },
  // {
  //   name: 'userSetting',
  //   path: '/setting/account',
  //   title: 'User Settings',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:every-user',
  //   componentPath: '/setting/account/index.vue',
  //   id: 36,
  //   pid: 35,
  // },
 
  
  {
    name: 'userSetting',
    path: '/Onboard/Agent',
    title: 'Agent',
    requiresAuth: true,
    icon: 'icon-park-outline:every-user',
    componentPath: '/setting/account/index.vue',
    id: 37,
    pid: 36,
  },
  {
    name: 'generalSetting',
    path: '/AddOns/Plugins',
    title: 'Plugins',
    requiresAuth: true,
    icon: 'icon-park-outline:plug-one',
    componentPath: '/onboard/plugins/plugins.vue',
    id: 53,
    pid: 200,
  },
  {
    name: 'Linux Client Registration',
    path: '/Onboard/Linux',
    title: 'Linux Client Registration',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/onboard/linux/index.vue',
    id: 50,
    pid: 36,
  },
  {
    name: 'Windows Client Registration',
    path: '/Onboard/Windows',
    title: 'Windows Client Registration',
    requiresAuth: true,
    icon: 'icon-park-outline:windows',
    componentPath: '/onboard/windows/index.vue',
    id: 51,
    pid: 36,
  },
  
 
  
  {
    name: 'SOC Wazuh',
    path: '/soc',
    title: 'SOC Wazuh',
    requiresAuth: true,
    icon: 'icon-park-outline:book-one',
    hide: true,
    // menuType: 'dir',
    componentPath: '/SOC_Wazuh/soc.vue',
    id: 39,
    pid: null,

  },
  {
    name: 'Wazuh2',
    path: '/wazuh2', // Unique path for Wazuh2
    title: 'Wazuh2',
    requiresAuth: true,
    icon: 'carbon:data-error',
    hide: true,
    // menuType: 'dir',
    componentPath: '/Wazuh2/wazuh2.vue',
    id: 40,
    pid: null,
  },
  {
    name: 'Wazuh3',
    path: '/wazuh3', // Unique path for Wazuh2
    title: 'Wazuh3',
    requiresAuth: true,
    icon: 'carbon:data-error',
    hide: true,
    // menuType: 'dir',
    componentPath: '/Wazuh3/wazuh3.vue',
    id: 41,
    pid: null,

  },
  // {
  //   name: 'activatedPlugins',
  //   path: '/activated-plugins',
  //   title: 'Activated Plugins',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:book-one',
  //   componentPath: '/activatedPlugin/index.vue',
  //   id: 43,
  //   pid: 200,
  // },
  {
    name: 'summary',
    path: '/summary',
    title: 'Summary',
    requiresAuth: true,
    hide: true,
    icon: 'icon-park-outline:book-one',
    componentPath: '/activatedPlugin/summary.vue',
    id: 44,
    pid: null,
  },
  {
    name: 'compliance',
    path: '/compliance',
    title: 'Compliance',
    requiresAuth: true,
    hide: true,
    icon: 'icon-park-outline:book-one',
    componentPath: '/activatedPlugin/compliance.vue',
    id: 45,
    pid: null,
  },
  {
    name: 'fileIntegrity',
    path: '/fileIntegrity',
    title: 'File Integrity Monitoring',
    requiresAuth: true,
    hide: true,
    icon: 'icon-park-outline:book-one',
    componentPath: '/activatedPlugin/fileIntegrity.vue',
    id: 46,
    pid: null,
  },
  {
    name: 'mitreAttack',
    path: '/mitreAttack',
    title: 'Mitre Attack',
    requiresAuth: true,
    hide: true,
    icon: 'icon-park-outline:book-one',
    componentPath: '/activatedPlugin/mitreAttack.vue',
    id: 47,
    pid: null,
  },
  {
    name: 'windowsEvent',
    path: '/windowsEvent',
    title: 'Windows Event Logs',
    requiresAuth: true,
    hide: true,
    icon: 'icon-park-outline:book-one',
    componentPath: '/activatedPlugin/windowsEvent.vue',
    id: 48,
    pid: null,
  },
  // {
  //   name: 'dashboard',
  //   path: '/dashboard',
  //   title: 'Dashboard',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:analysis',
  //   componentPath: '/monitoring/dashboard.vue',
  //   id: 1,
  //   pid: null,
  // },
  {
    name: "Databases",
    path: "/databases",
    title: "Databases",
    requiresAuth: true,
    icon: 'icon-park-outline:database-config',
    componentPath: "/databases/index.vue",
    id: 100,
    pid: null
  },
  {
    name: "Postgres",
    path: "/databases/postgres",
    title: "PostgreSQL",
    requiresAuth: true,
    hide: true,
    icon: "icon-park-outline:list",
    menuType: "page",
    componentPath: "/databases/postgres.vue",
    id: 101,
    pid: null
  },
  {
    name: "MongoDB",
    path: "/databases/mongodb",
    title: "MongoDB",
    requiresAuth: true,
    hide: true,
    icon: "icon-park-outline:list",
    menuType: "page",
    componentPath: "/databases/mongodb.vue",
    id: 102,
    pid: null
  },
  {
    name: "MySQL",
    path: "/databases/mysql",
    title: "MySQL",
    requiresAuth: true,
    hide: true,
    icon: "icon-park-outline:list",
    menuType: "page",
    componentPath: "/databases/mysql.vue",
    id: 103,
    pid: null
  },
  {
    name: "MS SQL",
    path: "/databases/mssql",
    title: "Microsoft SQL Server",
    requiresAuth: true,
    hide: true,
    icon: "icon-park-outline:list",
    menuType: "page",
    componentPath: "/databases/mssql.vue",
    id: 104,
    pid: null
  },
  {
    name: "Oracle DB",
    path: "/databases/oracledb",
    title: "Oracle DB",
    requiresAuth: true,
    hide: true,
    icon: "icon-park-outline:list",
    menuType: "page",
    componentPath: "/databases/oracle.vue",
    id: 105,
    pid: null
  },
  // {
  //   name: "DevOps Monitoring",
  //   path: "/devops-monitoring",
  //   title: "DevOps Monitoring",
  //   requiresAuth: true,
  //   icon: "carbon:ibm-devops-control",
  //   menuType: "dir",
  //   componentPath: null,
  //   id: 106,
  //   pid: null
  // },
  // {
  //   name: "SUSE Manager",
  //   path: "/devops-monitoring/suse-manager",
  //   title: "SUSE Manager",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/devops-monitoring/suse-manager.vue",
  //   id: 107,
  //   pid: 106
  // },
  // {
  //   name: "Uyuni",
  //   path: "/devops-monitoring/uyuni",
  //   title: "Uyuni",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/devops-monitoring/uyuni.vue",
  //   id: 108,
  //   pid: 106
  // },
  // {
  //   name: "SUSE High Availability Server",
  //   path: "/devops-monitoring/suse-ha",
  //   title: "SUSE High Availability Server",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/devops-monitoring/suse-ha.vue",
  //   id: 109,
  //   pid: 106
  // },
  // {
  //   name: "CI/CD Monitoring",
  //   path: "/cicd-monitoring",
  //   title: "CI/CD Monitoring",
  //   requiresAuth: true,
  //   icon: 'tabler:settings-automation',
  //   menuType: "dir",
  //   componentPath: null,
  //   id: 110,
  //   pid: null
  // },
  // {
  //   name: "GitLab",
  //   path: "/cicd-monitoring/gitlab",
  //   title: "GitLab",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/cicd-monitoring/gitlab.vue",
  //   id: 111,
  //   pid: 110
  // },
  // {
  //   name: "Jenkins",
  //   path: "/cicd-monitoring/jenkins",
  //   title: "Jenkins",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/cicd-monitoring/jenkins.vue",
  //   id: 112,
  //   pid: 110
  // },
  // {
  //   name: "Ansible",
  //   path: "/cicd-monitoring/ansible",
  //   title: "Ansible",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/cicd-monitoring/ansible.vue",
  //   id: 113,
  //   pid: 110
  // },
  // {
  //   name: "Virtualization Infra Monitoring",
  //   path: "/virtualization-infra",
  //   title: "Virtualization Infra Monitoring",
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:analysis',
  //   menuType: "dir",
  //   componentPath: null,
  //   id: 114,
  //   pid: null
  // },
  // {
  //   name: "XCP-ng",
  //   path: "/virtualization-infra/xcp-ng",
  //   title: "XCP-ng - XenServer",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/virtualization-infra/xcp-ng.vue",
  //   id: 115,
  //   pid: 114
  // },
  // {
  //   name: "HyperV",
  //   path: "/virtualization-infra/hyperv",
  //   title: "HyperV",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/virtualization-infra/hyperv.vue",
  //   id: 116,
  //   pid: 114
  // },
  // {
  //   name: "Kubevirt",
  //   path: "/virtualization-infra/kubevirt",
  //   title: "Kubevirt",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/virtualization-infra/kubevirt.vue",
  //   id: 117,
  //   pid: 114
  // },
  // {
  //   name: "KVM",
  //   path: "/virtualization-infra/kvm",
  //   title: "KVM",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/virtualization-infra/kvm.vue",
  //   id: 118,
  //   pid: 114
  // },
  // {
  //   name: "LXD Container",
  //   path: "/virtualization-infra/lxd",
  //   title: "LXD Container",
  //   requiresAuth: true,
  //   icon: "icon-park-outline:list",
  //   menuType: "page",
  //   componentPath: "/virtualization-infra/lxd.vue",
  //   id: 119,
  //   pid: 114
  // },

  // {
  //   name: 'Private Clouds',
  //   path: '/private-clouds',
  //   title: 'Private Clouds',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:link-cloud-sucess',
  //   menuType: 'dir',
  //   componentPath: null,
  //   id: 120,
  //   pid: null,
  // },
  // {
  //   name: 'OpenStack',
  //   path: '/private-clouds/openstack',
  //   title: 'OpenStack',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   menuType: 'page',
  //   componentPath: '/private-clouds/openstack.vue',
  //   id: 121,
  //   pid: 120,
  // },
  // {
  //   name: 'CloudStack',
  //   path: '/private-clouds/cloudstack',
  //   title: 'CloudStack',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   menuType: 'page',
  //   componentPath: '/private-clouds/cloudstack.vue',
  //   id: 122,
  //   pid: 120,
  // },
  // {
  //   name: 'Harvester',
  //   path: '/private-clouds/harvester',
  //   title: 'Harvester',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   menuType: 'page',
  //   componentPath: '/private-clouds/harvester.vue',
  //   id: 123,
  //   pid: 120,
  // },
  // {
  //   name: 'Proxmox',
  //   path: '/private-clouds/proxmox',
  //   title: 'Proxmox',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   menuType: 'page',
  //   componentPath: '/private-clouds/proxmox.vue',
  //   id: 124,
  //   pid: 120,
  // },

  // {
  //   name: 'Container Runtimes',
  //   path: '/container-runtimes',
  //   title: 'Container Runtimes',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:box',
  //   menuType: 'dir',
  //   componentPath: null,
  //   id: 125,
  //   pid: null,
  // },
  // {
  //   name: 'Podman',
  //   path: '/container-runtimes/podman',
  //   title: 'Podman',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   menuType: 'page',
  //   componentPath: '/container-runtimes/podman.vue',
  //   id: 126,
  //   pid: 125,
  // },
  // {
  //   name: 'Docker',
  //   path: '/container-runtimes/docker',
  //   title: 'Docker',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   menuType: 'page',
  //   componentPath: '/container-runtimes/docker.vue',
  //   id: 127,
  //   pid: 125,
  // },
  // {
  //   name: 'Cri-o',
  //   path: '/container-runtimes/crio',
  //   title: 'Cri-o',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:list',
  //   menuType: 'page',
  //   componentPath: '/container-runtimes/crio.vue',
  //   id: 128,
  //   pid: 125,
  // },
  {
    name: 'Onboard',
    path: '/Onboard',
    title: 'Onboard',
    requiresAuth: true,
    icon: 'icon-park-outline:setting',
    menuType: 'dir',
    componentPath: null,
    id: 36,
    pid: null,
  },
  {
    name: 'Ad-Ons',
    path: '/AddOns',
    title: 'Ad-Ons',
    requiresAuth: true,
    icon: 'icon-park-outline:app-store',
    menuType: 'dir',
    componentPath: null,
    id: 200,
    pid: null,
  },
  

]

