apiVersion: v1
kind: Service
metadata:
  name: postgres-kubeconfig
  labels:
    app: postgres-kubeconfig
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-kubeconfig
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-kubeconfig
spec:
  selector:
    matchLabels:
      app: postgres-kubeconfig
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-kubeconfig
    spec:
      containers:
      - image: postgres:14-alpine
        name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: kubeconfig-db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubeconfig-db-credentials
              key: password
        - name: POSTGRES_DB
          value: kubeconfig_db
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-kubeconfig-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-kubeconfig-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
