apiVersion: v1
kind: Secret
metadata:
  name: chat-db-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cG9zdGdyZXM=  # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
data:
  password: ""  # Base64 encoded password if needed
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
data:
  username: Z3Vlc3Q=  # guest (base64 encoded)
  password: Z3Vlc3Q=  # guest (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-credentials
type: Opaque
data:
  api-key: YOUR_BASE64_ENCODED_OPENAI_API_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  key: YOUR_BASE64_ENCODED_JWT_SECRET
