apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
  labels:
    app: user-auth-service
spec:
  selector:
    app: user-auth-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
