role_permissions = {
    "Super Admin": ["all"],

    "platform_engineer": [
        "dashboard",
        "clusters",
        "applications",
        "workloads",
        "analyze",
        "chatops",
        "insights",
        "observability",
        "carbon-emission",
        "cost",
        "backup",
        "security",
        "settings",
        "integrations",
        "help",
    ],

    "devops": [
        "dashboard",
        "clusters",
        "applications",
        "workloads",
        "chatops",
        "insights",
        "observability",
        "cost",
        "remediations",
        "backup",
        "settings",
        "integrations",
        "help",
    ],

    "developer": [
        "dashboard",
        "clusters",
        "applications",
        "workloads",
        "observability",
        "analyze",
        "chatops",
        "insights",
        "settings",
        "help",
    ],

    "security_engineer": [
        "dashboard",
        "clusters",
        "security",
        "secrets",
        "compliance",
        "remediations",
        "anomalies",
        "settings",
        "help",
    ]
}
